name: Setup Environment
description: Setup Environment File

runs:
  using: "composite"
  steps:
    - name: Setup Environment
      run: |
        cp .env.example .env.test
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env.test
        echo "API_URL=${{ secrets.API_URL }}" >> .env.test
      shell: bash
