name: "Chromatic"

on:
  pull_request:
    paths:
      - "src/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".env.example"

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

    # 制限に達した + 完成したのでコメントアウト

    # - name: Setup pnpm
    #   uses: ./.github/actions/setup-pnpm

    # - name: Run Chromatic
    #   uses: chromaui/action@latest
    #   with:
    #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    #     buildScriptName: "sb:build"
